language: node_js
node_js:
  - '0.10'
  - '0.11'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y clang-3.4 

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: friedsilicon:3GVMf1aqtsnaV8Hrc9FIB28X

before_script:
  - npm install -g istanbul
  - npm install -g codeclimate-test-reporter

script:
  - export LD_LIBRARY_PATH=/usr/local/clang-3.4/lib/:$LD_LIBRARY_PATH
  - npm run-script test

after_success:
  - npm run-script codeclimate
  - npm run-script coveralls
  - npm run-script clean-coverage
