language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.11'
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - node_modules
notifications:
  slack: friedsilicon:3GVMf1aqtsnaV8Hrc9FIB28X
